# Prepare proteomic data - RBC Omics
## Setup
### Import packages

In [1]:
from pathlib import Path

import pandas as pd
from rbc_gem_utils import COBRA_CONFIGURATION, ROOT_PATH, show_versions
from rbc_gem_utils.util import AVOGADRO_NUMBER

# Show versions of notebook
show_versions()

Package Information
-------------------
rbc-gem-utils 0.0.1

Dependency Information
----------------------
beautifulsoup4                       4.12.3
bio                                 missing
cobra                                0.29.1
depinfo                               2.2.0
gurobipy                             11.0.3
matplotlib                           3.10.0
matplotlib-venn                       1.1.1
memote                               0.17.0
networkx                              3.4.2
notebook                              7.3.2
openpyxl                              3.1.5
pandas                                2.2.3
pre-commit                            4.1.0
rbc-gem-utils[database,network,vis] missing
requests                             2.32.3
scipy                                1.15.1
seaborn                              0.13.2

Build Tools Information
-----------------------
pip          24.2
setuptools 75.1.0
wheel      0.44.0

Platform Information
--------------------
Windows 11-AMD64
CPython   3.12.8

### Define configuration
#### COBRA Configuration

In [2]:
COBRA_CONFIGURATION.solver = "gurobi"
COBRA_CONFIGURATION.bounds = (-1e3, 1e3)
COBRA_CONFIGURATION

solver: gurobi
tolerance: 1e-07
lower_bound: -1000.0
upper_bound: 1000.0
processes: 127
cache_directory: C:\Users\Alicia Key\AppData\Local\opencobra\cobrapy\Cache
max_cache_size: 104857600
cache_expiration: None

## Load RBC-GEM model

In [3]:
# data_path = Path("../../../../data/analysis/OVERLAY").resolve()
# dataset_name = "RBComics"
# df_omics_path = data_path / dataset_name / f"{dataset_name}.tsv"
# df_protein_data_path = data_path / dataset_name / f"{dataset_name}_protein_data.tsv"

data_path = Path("../../../../data/analysis/OVERLAY").resolve()
dataset_name = "RBComics_G6PD"
df_omics_path = data_path / dataset_name / "TIntensitiesUniprot.csv"
df_protein_data_path = data_path / dataset_name / "TUniProtMapping.csv"
df_metadata_path = data_path / dataset_name / "TDonorMetadata.csv"

print(df_omics_path)
print(df_protein_data_path)

D:\Projects\RBC-GEM-akey7\data\analysis\OVERLAY\RBComics_G6PD\TIntensitiesUniprot.csv
D:\Projects\RBC-GEM-akey7\data\analysis\OVERLAY\RBComics_G6PD\TUniProtMapping.csv

## Load RBC Proteomics

In [4]:
# df_omics = pd.read_csv(
#     df_omics_path, sep="\t", index_col=False
# )
# df_protein_data = pd.read_csv(
#     df_protein_data_path,
#     sep="\t",
#     index_col="Entry",
# )

# df_uniprot_to_mw = df_protein_data["Mass"] / 1000
# df_metadata = (
#     df_omics.groupby("INDEX ID")[df_omics.columns[2:30]]
#     .agg(lambda x: list(x.unique())[0])
#     .reset_index(drop=False)
# )

# # Fill missing data with average
# df_hb_per_sample = df_metadata.set_index("INDEX ID")["CBC.HGB"] * 2
# df_hb_per_sample = df_hb_per_sample.fillna(round(df_hb_per_sample.mean(), 1))

# df_proteomics = df_omics.loc[
#     :, list(df_omics.columns[:2]) + list(df_omics.columns[30:])
# ].copy()
# df_proteomics = df_proteomics.loc[
#     :, [x for x in df_proteomics.columns if not str(x[0]).isnumeric()]
# ]

In [5]:
df_proteomics = pd.read_csv(df_omics_path, index_col=False)
df_proteomics

,public_donor_id,Day,P69905,P68871,P02042,P02008,P02730,P30043,P32119,P02768,...,Q9Y3E7,Q9Y4Y9,Q9Y508,Q9Y587,Q9Y5B8,Q9Y5P4,Q9Y5Y2,Q9Y666,Q9Y6B7,Q9Y6M4
0,AK_00001,10,224795.6875,126844.82030,317519.8750,62601.27344,109552.32810,50831.16797,19182.85938,38526.62891,...,0.000000,0.000000,0.00000,0.000000,36.817677,0.0,0.000000,0.000000,10.642120,0.000000
1,AK_00001,23,157363.4844,71241.86719,163391.4531,51302.66797,94158.84376,49155.95703,28512.68945,17376.78516,...,34.283047,20.184967,0.00000,43.162395,105.859085,0.0,211.974030,0.000000,12.084346,0.000000
2,AK_00001,42,264132.3125,45004.68750,376938.8750,98627.46094,118924.14060,63342.69922,33579.28906,31121.88867,...,30.149935,15.415367,0.00000,0.000000,0.000000,0.0,0.000000,0.000000,5.309950,17.121681
3,AK_00002,10,288401.0000,60522.73047,459202.5625,114409.22660,130365.96090,72633.82813,30194.57031,28979.78906,...,0.000000,0.000000,28.83349,10.425157,3.988680,0.0,0.000000,63.362873,0.000000,0.000000
4,AK_00002,23,224598.1563,126733.42190,319098.1875,105047.16410,118582.33590,66112.23438,32312.08789,21476.43750,...,67.144516,0.000000,0.00000,0.000000,0.000000,0.0,57.122700,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,AK_00650,10,203598.1250,146786.53130,321086.5625,92589.64844,132088.71880,57377.18750,27083.04297,18686.76563,...,0.000000,46.347740,0.00000,0.000000,89.357407,0.0,0.000000,0.000000,0.000000,0.000000
1911,AK_00650,23,191070.4844,126492.43750,244520.5938,91219.73438,112941.47660,54176.91797,25423.23242,16942.68164,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,41.203438,9.517267,0.000000,35.317646
1912,AK_00650,42,194644.7656,122276.07030,229019.5156,75837.22656,111903.94530,52238.39063,24713.06641,16980.49609,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,58.135319,0.000000,0.000000,1436.664917
1913,AK_00651,10,194732.1094,119638.66410,247365.3125,76368.24219,112854.51560,53275.36719,20377.37695,14438.47559,...,0.000000,0.000000,0.00000,0.000000,0.000000,0.0,120.188866,0.000000,8.334302,0.000000
1914,AK_00651,42,201346.2813,144212.10940,220198.2813,91041.76563,116009.58590,58525.91406,28750.92969,14530.74512,...,0.000000,0.000000,0.00000,0.000000,133.935730,0.0,0.000000,0.000000,7.708261,0.000000

In [6]:
df_metadata = pd.read_csv(df_metadata_path)
df_metadata

,public_donor_id,Day,AS,Gender,DONDB.ABO_RH,RBCOmics.Race.Ethnicity.Group,Age,BMI,Weight,Height,...,Adjusted.Osmotic.Hemolysis,Adjusted.Oxidative.Hemolysis,CBC.WBC,CBC.RBC,CBC.HGB,CBC.HCT,CBC.MCV,CBC.RDW,CBC.PLT,Ferritin
0,AK_00001,10,AS3,F,O+,CAUCASIAN,19,24.126627,145,65,...,25.115126,NaN,7.87,4.20,12.2,36.4,86.7,12.8,261.0,34.0
1,AK_00001,23,AS3,F,O+,CAUCASIAN,19,24.126627,145,65,...,25.115126,NaN,7.87,4.20,12.2,36.4,86.7,12.8,261.0,34.0
2,AK_00001,42,AS3,F,O+,CAUCASIAN,19,24.126627,145,65,...,25.115126,NaN,7.87,4.20,12.2,36.4,86.7,12.8,261.0,34.0
3,AK_00002,10,AS3,M,A-,HIGH,46,27.464398,186,69,...,53.047355,NaN,8.48,4.68,14.0,41.5,88.7,14.3,208.0,26.0
4,AK_00002,23,AS3,M,A-,HIGH,46,27.464398,186,69,...,53.047355,NaN,8.48,4.68,14.0,41.5,88.7,14.3,208.0,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1910,AK_00650,10,AS1,F,O+,CAUCASIAN,60,30.102509,198,68,...,42.290107,NaN,5.91,4.62,13.8,42.3,91.6,13.6,199.0,23.0
1911,AK_00650,23,AS1,F,O+,CAUCASIAN,60,30.102509,198,68,...,42.290107,NaN,5.91,4.62,13.8,42.3,91.6,13.6,199.0,23.0
1912,AK_00650,42,AS1,F,O+,CAUCASIAN,60,30.102509,198,68,...,42.290107,NaN,5.91,4.62,13.8,42.3,91.6,13.6,199.0,23.0
1913,AK_00651,10,AS1,F,O+,HIGH,80,30.996473,175,63,...,16.894124,32.578442,7.02,4.58,13.8,43.9,95.9,14.9,253.0,13.0
1914,AK_00651,42,AS1,F,O+,HIGH,80,30.996473,175,63,...,16.894124,32.578442,7.02,4.58,13.8,43.9,95.9,14.9,253.0,13.0

In [7]:
df_protein_data = pd.read_csv(df_protein_data_path)
df_protein_data

,Protein,ID,Entry,Protein names,Gene Names,Length,Mass
0,HBA,HBA_HUMAN,P69905,Hemoglobin subunit alpha (Alpha-globin) (Hemog...,HBA1; HBA2,142.0,15258.0
1,HBB,HBB_HUMAN,P68871,Hemoglobin subunit beta (Beta-globin) (Hemoglo...,HBB,147.0,15998.0
2,HBD,HBD_HUMAN,P02042,Hemoglobin subunit delta (Delta-globin) (Hemog...,HBD,147.0,16055.0
3,HBAZ,HBAZ_HUMAN,P02008,Hemoglobin subunit zeta (HBAZ) (Hemoglobin zet...,HBZ HBZ2,142.0,15637.0
4,B3AT,B3AT_HUMAN,P02730,Band 3 anion transport protein (Anion exchange...,SLC4A1 AE1 DI EPB3,911.0,101792.0
...,...,...,...,...,...,...,...
1847,CERT,CERT_HUMAN,Q9Y5P4,Ceramide transfer protein (hCERT) (Collagen ty...,CERT1 CERT COL4A3BP STARD11,624.0,70835.0
1848,NUBP2,NUBP2_HUMAN,Q9Y5Y2,Cytosolic Fe-S cluster assembly factor NUBP2 (...,NUBP2,271.0,28825.0
1849,S12A7,S12A7_HUMAN,Q9Y666,Solute carrier family 12 member 7 (Electroneut...,SLC12A7 KCC4,1083.0,119106.0
1850,AP4B1,AP4B1_HUMAN,Q9Y6B7,AP-4 complex subunit beta-1 (AP-4 adaptor comp...,AP4B1,739.0,83260.0
1851,KC1G3,KC1G3_HUMAN,Q9Y6M4,Casein kinase I isoform gamma-3 (CKI-gamma 3) ...,CSNK1G3,447.0,51389.0

In [8]:
df_uniprot_to_mw = df_protein_data["Mass"] / 1000
df_uniprot_to_mw.head()

0     15.258
1     15.998
2     16.055
3     15.637
4    101.792
Name: Mass, dtype: float64

In [9]:
# df_hb_per_sample = df_metadata.set_index("public_donor_id")["CBC.HGB"] * 2
# df_hb_per_sample = df_hb_per_sample.fillna(round(df_hb_per_sample.mean(), 1))
# df_hb_per_sample

### Transform sample intensities to copy numbers

In [10]:
df_copy_numbers = {}
df_conc_per_sample = {}
uniprot_ids = set()
min_copy_number = 0

#### Day 10

In [12]:
# Day is 10, 23, or 42
day = 10
df_hb_per_sample = df_metadata[df_metadata["Day"] == day].set_index("public_donor_id")["CBC.HGB"] * 2
df_hb_per_sample = df_hb_per_sample.fillna(round(df_hb_per_sample.mean(), 1))
df_proteomics_day = df_proteomics.set_index(["Day", "public_donor_id"]).loc[day]
df_proteomics_day = df_proteomics_day.apply(lambda x: x / x.sum(), axis=1)
# pmol / mgDW sample --> nmol / gDW sample
df_proteomics_day = (df_proteomics_day * 1e6) / df_uniprot_to_mw
df_conc_per_sample[day] = df_proteomics_day.copy()

# Normalize using each individuals CBC.HGB
df_proteomics_day = (
    (df_proteomics_day.T * 1e-9) * (df_hb_per_sample * 1e-12) * AVOGADRO_NUMBER
)
df_copy_numbers[day] = df_proteomics_day.T
df_proteomics_day

public_donor_id,AK_00001,AK_00002,AK_00003,AK_00004,AK_00005,AK_00006,AK_00007,AK_00008,AK_00009,AK_00010,...,AK_00642,AK_00643,AK_00644,AK_00645,AK_00646,AK_00647,AK_00648,AK_00649,AK_00650,AK_00651
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Q9Y6E0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q9Y6I3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q9Y6M4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q9Y6M5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q9Y6R7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Day 23

In [ ]:
# Day is 10, 23, or 42
day = 23
df_proteomics_day = df_proteomics.set_index(["Day", "public_donor_id"]).loc[day]
df_proteomics_day = df_proteomics_day.apply(lambda x: x / x.sum(), axis=1)
# pmol / mgDW sample --> nmol / gDW sample
df_proteomics_day = (df_proteomics_day * 1e6) / df_uniprot_to_mw
df_conc_per_sample[day] = df_proteomics_day.copy()

# Normalize using each individuals CBC.HGB
df_proteomics_day = (
    (df_proteomics_day.T * 1e-9) * (df_hb_per_sample * 1e-12) * AVOGADRO_NUMBER
)
df_copy_numbers[day] = df_proteomics_day.T
df_proteomics_day

#### Day 42

In [ ]:
# Day is 10, 23, or 42
day = 42
df_proteomics_day = df_proteomics.set_index(["Day", "public_donor_id"]).loc[day]
df_proteomics_day = df_proteomics_day.apply(lambda x: x / x.sum(), axis=1)
# pmol / mgDW sample --> nmol / gDW sample
df_proteomics_day = (df_proteomics_day * 1e6) / df_uniprot_to_mw
df_conc_per_sample[day] = df_proteomics_day.copy()

# Normalize using each individuals CBC.HGB
df_proteomics_day = (
    (df_proteomics_day.T * 1e-9) * (df_hb_per_sample * 1e-12) * AVOGADRO_NUMBER
)
df_copy_numbers[day] = df_proteomics_day.T
df_proteomics_day

### Export absolute quantitative data

In [ ]:
days = [10, 23, 42]
for day in days:
    df_conc_per_sample[day]["Day"] = day
    df_copy_numbers[day]["Day"] = day

df_concentrations_all = (
    pd.concat([df_conc_per_sample[day] for day in days], axis=0)
    .reset_index(drop=False)
    .set_index(["INDEX ID", "Day"])
)
df_concentrations_all.index = [f"S{x[0]}_D{x[1]}" for x in df_concentrations_all.index]

df_concentrations_all_path = data_path / dataset_name / "Proteomics_Concentrations.tsv"
df_concentrations_all.to_csv(
    df_concentrations_all_path, sep="\t", index=True
)

df_copy_number_all = (
    pd.concat([df_copy_numbers[day] for day in days], axis=0)
    .reset_index(drop=False)
    .set_index(["INDEX ID", "Day"])
)
df_copy_number_all.index = [f"S{x[0]}_D{x[1]}" for x in df_copy_number_all.index]

df_copy_number_all_path = data_path / dataset_name / "Proteomics_CopyNumbers.tsv"
df_copy_number_all.to_csv(
    df_copy_number_all_path, sep="\t", index=True
)
df_copy_number_all

### Export metadata

In [ ]:
df_metadata.head()

In [ ]:
df_metadata = df_metadata.set_index("INDEX ID")
df_metadata.index = [f"S{x}" for x in df_metadata.index]
df_metadata_path = data_path / dataset_name / "Proteomics_Metadata.tsv"
df_metadata.to_csv(
    df_metadata_path, sep="\t", index=True
)

df_metadata