In [1]:
from pathlib import Path
import pandas as pd
from rbc_gem_utils import FluxOptimizationAggregator

In [2]:
model_id = "RBC3P_expanded"
dataset_name = "RBComics_G6PD"
data_path = Path("../../../../data/analysis/OVERLAY").resolve()
root_path = Path("../../../..").resolve()
results_path = root_path / "data" / "processed" / model_id / "OVERLAY"
pcmodel_dirpath = data_path / model_id
dataset_path = results_path / dataset_name
dataset_models_dirpath = dataset_path / "pcmodels"
pcfva_results_dirpath = dataset_path / "pcFVA"
corr_results_dirpath = dataset_path / "correlations"
df_pcfva_all_filename = pcfva_results_dirpath / f"{model_id}_PC_FVAresults_ALL.tsv"
model_filename = pcmodel_dirpath / f"{model_id}.xml"
pcmodel_filename = pcmodel_dirpath / f"{model_id}_PC.xml"
correlations2_dirpath = dataset_path / "correlations2"
flux_plots_path = dataset_path / "flux_plots"
df_pcfva_alleles_filename = correlations2_dirpath / "df_pcfva_alleles.csv"
df_ranked_pct_diff_filename = correlations2_dirpath / "df_ranked_pct_differences.csv"

print(results_path)
print(pcmodel_dirpath)
print(dataset_path)
print(dataset_models_dirpath)
print(pcfva_results_dirpath)
print(corr_results_dirpath)
print(df_pcfva_all_filename)
print(model_filename)
print(pcmodel_filename)
print(correlations2_dirpath)
print(flux_plots_path)
print(df_pcfva_alleles_filename)
print(df_ranked_pct_diff_filename)

D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY
D:\Projects\RBC-GEM-akey7\data\analysis\OVERLAY\RBC3P_expanded
D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY\RBComics_G6PD
D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY\RBComics_G6PD\pcmodels
D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY\RBComics_G6PD\pcFVA
D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY\RBComics_G6PD\correlations
D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY\RBComics_G6PD\pcFVA\RBC3P_expanded_PC_FVAresults_ALL.tsv
D:\Projects\RBC-GEM-akey7\data\analysis\OVERLAY\RBC3P_expanded\RBC3P_expanded.xml
D:\Projects\RBC-GEM-akey7\data\analysis\OVERLAY\RBC3P_expanded\RBC3P_expanded_PC.xml
D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY\RBComics_G6PD\correlations2
D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY\RBComics_G6PD\flux_plots
D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY\RBComics_G6PD\correlations2\df_pcfva_alleles.csv
D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY\RBComics_G6PD\correlations2\df_ranked_pct_differences.csv

TODO: Shut off `RELAX_protein_G6PD_pc` by setting this reaction's bounds to 0, 0. Add `G6PDH2` to `NaKt` as the objective.

In [3]:
flux_optimization_aggregator = FluxOptimizationAggregator(
    df_pcfva_alleles_filename=df_pcfva_alleles_filename
)
df_average_range_by_allele = flux_optimization_aggregator.average_by_allele(
    optimum=0.99
)
df_average_range_by_allele.query("reactions == 'G6PDH2'").query("reactions == 'G6PDH2'")

     reactions  G6PD_alleles  minimum   maximum     range
2421    G6PDH2             0      0.0  0.018673  0.018673
2422    G6PDH2             1      0.0  0.008623  0.008623
2423    G6PDH2             2      0.0  0.001843  0.001843

In [4]:
(0.015 / 0.034) - 1

-0.5588235294117647

In [5]:
flux_optimization_aggregator.pct_diff_compared_to_baseline(
    df_average_range_by_allele,
    reaction="G6PDH2",
    baseline_alleles=0,
    comparison_alleles=2,
)

{'minimum_pct_diff': <NA>,
 'maximum_pct_diff': np.float64(-0.9012953624179091),
 'range_pct_diff': np.float64(-0.9012953624179091)}

In [6]:
df_ranked_pct_diff = flux_optimization_aggregator.pct_diff_compared_to_baseline_all_reactions(
    df_average_range_by_allele, baseline_alleles=0, comparison_alleles=2
)
df_ranked_pct_diff

,minimum_pct_diff,maximum_pct_diff,range_pct_diff,abs_range_pct_diff,reaction
7,<NA>,-0.901295,-0.901295,0.901295,BILIREDy
31,<NA>,-0.901295,-0.901295,0.901295,HOXG
8,<NA>,-0.901295,-0.901295,0.901295,BILRUBABCte
22,<NA>,-0.901295,-0.901295,0.901295,GND
20,<NA>,-0.901295,-0.901295,0.901295,G6PDH2
...,...,...,...,...,...
10,<NA>,-0.002477,-0.002477,0.002477,CAATPS1
36,<NA>,-0.00028,-0.000280,0.000280,Kt1
38,<NA>,-0.000194,-0.000194,0.000194,NAt
9,<NA>,-0.000133,-0.000133,0.000133,CA2t
11,0.00526,-0.005422,-0.000075,0.000075,CO2t

In [7]:
df_ranked_pct_diff[["reaction", "range_pct_diff"]].to_csv(df_ranked_pct_diff_filename, index=False)