# Create representative Proteome-Constrained RBC model for dataset
## Setup
### Import packages

In [1]:
import itertools
from collections import defaultdict
from pathlib import Path

import gurobipy as gp
import pandas as pd
from rbc_gem_utils import (COBRA_CONFIGURATION, DATABASE_PATH, GEM_NAME,
                           PROCESSED_PATH, ROOT_PATH, build_string,
                           get_annotation_df, read_cobra_model, show_versions,
                           split_string, write_cobra_model)
from rbc_gem_utils.analysis.overlay import (
    ATTR_SUBCLASS_DICT, DEFAULT_COMPARTMENT_CONSTRAINT_PREFIX,
    DEFAULT_CONCENTRATION_BOUND, DEFAULT_CONSTRAINT_PREFIX,
    DEFAULT_ENZYME_FORWARD_SUFFIX, DEFAULT_ENZYME_REVERSE_SUFFIX,
    DEFAULT_ENZYME_TOTAL_SUFFIX, DEFAULT_ISOFORM_CONSTRAINT_PREFIX,
    DEFAULT_KEFF, ComplexDilution, Enzyme, EnzymeDilution, Protein,
    ProteinDilution, ProteomeBudget, ProteomeBudgetDilution,
    add_relaxation_budget, construct_pcmodel_from_tables, create_complex_table,
    create_enzyme_table, create_protein_table, create_sequence_table,
    load_overlay_model)
from rbc_gem_utils.database.uniprot import UNIPROT_DB_TAG, UNIPROT_PATH
from rbc_gem_utils.util import convert_gDW_to_L, convert_L_to_gDW, strip_plural

gp.setParam("OutputFlag", 0)
gp.setParam("LogToConsole", 0)

# Show versions of notebook
show_versions()

Set parameter Username

Package Information
-------------------
rbc-gem-utils 0.0.1

Dependency Information
----------------------
beautifulsoup4                       4.12.3
bio                                 missing
cobra                                0.29.1
depinfo                               2.2.0
gurobipy                             11.0.3
matplotlib                           3.10.0
matplotlib-venn                       1.1.1
memote                               0.17.0
networkx                              3.4.2
notebook                              7.3.2
openpyxl                              3.1.5
pandas                                2.2.3
pre-commit                            4.1.0
rbc-gem-utils[database,network,vis] missing
requests                             2.32.3
scipy                                1.15.1
seaborn                              0.13.2

Build Tools Information
-----------------------
pip          24.2
setuptools 75.1.0
wheel      0.44.0

Platform Information
--------------------
Windows 11-AMD64
CPython   3.12.8

### Define configuration
#### COBRA Configuration

In [2]:
COBRA_CONFIGURATION.solver = "gurobi"
COBRA_CONFIGURATION.bounds = (-1e8, 1e8)
COBRA_CONFIGURATION

solver: gurobi
tolerance: 1e-07
lower_bound: -100000000.0
upper_bound: 100000000.0
processes: 127
cache_directory: C:\Users\Alicia Key\AppData\Local\opencobra\cobrapy\Cache
max_cache_size: 104857600
cache_expiration: None

## Load RBC model

In [3]:
model_id = "RBC3P_expanded"

data_path = Path("../../../../data/analysis/OVERLAY").resolve()
root_path = Path("../../../..").resolve()
results_path = root_path / "data" / "processed" / model_id / "OVERLAY"
results_path.mkdir(exist_ok=True, parents=True)

imagetype = "svg"
transparent = True
save_figures = True

dataset_name = "RBComics_G6PD"
pcmodel_dirpath = data_path / model_id
dataset_path = results_path / dataset_name
dataset_models_dirpath = dataset_path / "pcmodels"

sample_prefix, time_prefix = ("S", "D")
# Integers are easier to work with for time points
timepoints = [10, 23, 42]

model_filename = pcmodel_dirpath / f"{model_id}.xml"
model = read_cobra_model(filename=model_filename)
pcmodel_filename = pcmodel_dirpath / f"{model_id}_PC.xml"
pcmodel = load_overlay_model(filename=pcmodel_filename)

# For this workflow, shut off complex dilution reactions at the start
for cplx_dilution in pcmodel.reactions.query(lambda x: isinstance(x, ComplexDilution)):
    cplx_dilution.bounds = (0, 0)

pcmodel

In [4]:
print(dataset_path)
print(model_filename)

D:\Projects\RBC-GEM-akey7\data\processed\RBC3P_expanded\OVERLAY\RBComics_G6PD
D:\Projects\RBC-GEM-akey7\data\analysis\OVERLAY\RBC3P_expanded\RBC3P_expanded.xml

### Create PC-model representative of dataset
Can only be done after pcFVA results are generated

In [5]:
sample_model_filename = dataset_models_dirpath / f"{model_id}_PC_Mean_D10.xml"
sample_model = load_overlay_model(filename=sample_model_filename)
sample_model.optimize()

In [6]:
df_reaction_ranges_filename = dataset_path / f"{pcmodel.id}_{dataset_name}_reaction_bounds.tsv"
df_reaction_bounds = pd.read_csv(
    df_reaction_ranges_filename,
    sep="\t",
    index_col="reactions",
)
df_reaction_bounds = df_reaction_bounds.rename(
    {"minimum": "lower_bound", "maximum": "upper_bound"}, axis=1
)
df_reaction_bounds

            lower_bound  upper_bound
reactions
ADA        0.000000e+00     4.410837
ADEt      -4.626114e-01     0.000000
ADK1      -1.110765e-16     0.462611
ADNK1      0.000000e+00     0.462611
ADNt      -4.243464e+00     0.462611
...                 ...          ...
SPODM      0.000000e+00     3.203140
TALA      -7.257304e-01     0.692508
TKT1      -7.257304e-01     0.692508
TKT2      -7.257304e-01     0.692508
TPI       -3.469447e-18     0.841568

[1080 rows x 2 columns]

In [7]:
pcmodel_dataset_parameterized = pcmodel.copy()
pcmodel_dataset_parameterized.id += f"_{dataset_name}"
add_relaxation_budget(pcmodel_dataset_parameterized, 0, verbose=False)
for rid, bounds in df_reaction_bounds.iterrows():
    reaction = pcmodel_dataset_parameterized.reactions.get_by_id(rid)
    reaction.bounds = bounds

original_relaxation_bounds = pcmodel_dataset_parameterized.reactions.get_by_id(
    "PBDL_relaxation_budget"
).bounds
# Protein constrained  without curated keffs
cobra_model_filename = pcmodel_dirpath / f"{pcmodel_dataset_parameterized}.xml"
write_cobra_model(
    pcmodel_dataset_parameterized, filename=cobra_model_filename
)
pcmodel_dataset_parameterized

In [8]:
pcmodel_dataset_parameterized.reactions.get_by_id("PBDL_relaxation_budget").upper_bound = 10.0
for reaction in pcmodel_dataset_parameterized.reactions:
    if "budget" in reaction.id.lower() or "relax" in reaction.id.lower():
        print(reaction.id, reaction.bounds)
pcmodel_dataset_parameterized.optimize()

PBDL_proteome_budget (4.535990744968091, 9.699597077807796)
PBDL_hemoglobin_budget (921.4999999999976, 950.000000000002)
PBDL_total_budget (926.0550520429526, 988.4905849901418)
PBDL_relaxation_budget (0.0013424251529841, 10.0)
RELAX_protein_ABCC4_pc (0.0, 5.77620416730595)
RELAX_protein_ADA_pc (0.0, 21.1937399950315)
RELAX_protein_ADK_pc (0.0, 21.3050696277198)
RELAX_protein_AK1_pc (0.0, 39.9178524317644)
RELAX_protein_ALDOA_pc (0.0, 21.9094573941383)
RELAX_protein_ALDOB_pc (0.0, 21.880587752916)
RELAX_protein_ALDOC_pc (0.0, 21.8923528676284)
RELAX_protein_AMPD3_pc (0.0, 9.7262012051026)
RELAX_protein_APRT_pc (0.0, 44.0553323214795)
RELAX_protein_AQP1_pc (0.0, 30.2789489568857)
RELAX_protein_AQP3_pc (0.0, 27.3830196727749)
RELAX_protein_ATP1A1_pc (0.0, 7.65229780393973)
RELAX_protein_ATP1A3_pc (0.0, 7.73110391864579)
RELAX_protein_ATP1A4_pc (0.0, 7.56606159554446)
RELAX_protein_ATP1B1_pc (0.0, 22.999885539967423)
RELAX_protein_ATP1B2_pc (0.0, 22.999885539967423)
RELAX_protein_ATP1B3_pc (0.0, 22.999885539967423)
RELAX_protein_ATP2B1_pc (0.0, 6.41399014692861)
RELAX_protein_ATP2B4_pc (0.0, 6.26300210761631)
RELAX_protein_BLVRA_pc (0.0, 25.8414809053966)
RELAX_protein_BLVRB_pc (0.0, 39.0489489547355)
RELAX_protein_BPGM_pc (0.0, 28.7901261278924)
RELAX_protein_BSG_pc (0.0, 20.4743815031259)
RELAX_protein_CACNA1A_pc (0.0, 3.05643732979347)
RELAX_protein_CYB5A_pc (0.0, 76.7197952370371)
RELAX_protein_CYB5B_pc (-4.996003610813205e-15, 51.7657891698582)
RELAX_protein_CYB5R3_pc (0.0, 27.308680041971)
RELAX_protein_EMB_pc (0.0, 23.4215245555164)
RELAX_protein_ENO1_pc (0.0, 18.311559127951)
RELAX_protein_ENO2_pc (0.0, 18.2799880696331)
RELAX_protein_ENO3_pc (-1.3877787807814454e-16, 18.3821265326247)
RELAX_protein_G6PD_pc (0.0, 14.5771793028917)
RELAX_protein_GAPDH_pc (0.0, 23.9552754066013)
RELAX_protein_GAPDHS_pc (0.0, 19.4080066182702)
RELAX_protein_GPI_pc (0.0, 13.6775244522299)
RELAX_protein_GPX1_pc (0.0, 39.1890534201489)
RELAX_protein_GPX4_pc (0.0, 44.3384980257564)
RELAX_protein_GRIA1_pc (0.0, 8.50905244504641)
RELAX_protein_GSR_pc (0.0, 16.7061955184104)
RELAX_protein_HBA_pc (0.0, 56.6030376098148)
RELAX_protein_HBB_pc (0.0, 53.9924025269625)
RELAX_protein_HBD_pc (0.0, 53.7936947364601)
RELAX_protein_HBE1_pc (0.0, 53.3012428550759)
RELAX_protein_HBG1_pc (0.0, 53.5571422989949)
RELAX_protein_HBG2_pc (0.0, 53.5636919323355)
RELAX_protein_HBM_pc (0.0, 55.3143493236527)
RELAX_protein_HBQ1_pc (0.0, 55.6970466662966)
RELAX_protein_HBZ_pc (0.0, 55.2331705194825)
RELAX_protein_HK1_pc (0.0, 8.45214470602748)
RELAX_protein_HK3_pc (0.0, 8.72477506918831)
RELAX_protein_HPRT1_pc (0.0, 35.1435829710235)
RELAX_protein_KCNAB2_pc (0.0, 21.0625083747857)
RELAX_protein_KCNK5_pc (0.0, 15.6681697707765)
RELAX_protein_KCNN4_pc (0.0, 18.1013585417632)
RELAX_protein_LDHA_pc (0.0, 23.5403658143269)
RELAX_protein_LDHB_pc (0.0, 23.5784722577832)
RELAX_protein_LHPP_pc (0.0, 29.6192802233785)
RELAX_protein_NT5C2_pc (0.0, 13.2973305854363)
RELAX_protein_P2RX1_pc (0.0, 19.199657547169)
RELAX_protein_P2RX2_pc (0.0, 16.687602007993)
RELAX_protein_P2RX7_pc (0.0, 12.5914584175492)
RELAX_protein_PANX1_pc (0.0, 17.9772661962135)
RELAX_protein_PFKL_pc (0.0, 10.1594049374806)
RELAX_protein_PFKM_pc (0.0, 10.1393547902051)
RELAX_protein_PFKP_pc (0.0, 10.090726707519)
RELAX_protein_PGAM1_pc (0.0, 29.9878510273997)
RELAX_protein_PGD_pc (0.0, 16.2542993257969)
RELAX_protein_PGK1_pc (0.0, 19.3586050432991)
RELAX_protein_PGK2_pc (0.0, 19.278900073259)
RELAX_protein_PGLS_pc (0.0, 31.3609577704368)
RELAX_protein_PGM2_pc (0.0, 12.6502419137716)
RELAX_protein_PIEZO1_pc (0.0, 3.01174703309522)
RELAX_protein_PKLR_pc (0.0, 13.9692899873667)
RELAX_protein_PKM_pc (0.0, 14.9077184410233)
RELAX_protein_PNP_pc (0.0, 26.8944110763568)
RELAX_protein_PPA1_pc (0.0, 26.4528269472698)
RELAX_protein_PPA2_pc (0.0, 22.7777379755506)
RELAX_protein_PRPS1_pc (0.0, 24.7970551792927)
RELAX_protein_PRPS1L1_pc (0.0, 24.7955851814253)
RELAX_protein_PRPS2_pc (0.0, 24.8449441143143)
RELAX_protein_PRUNE1_pc (0.0, 17.2126163126009)
RELAX_protein_RHAG_pc (0.0, 19.5438259925151)
RELAX_protein_RHCE_pc (0.0, 11.176013678156425)
RELAX_protein_RHD_pc (0.0, 12.145752931694446)
RELAX_protein_RPE_pc (0.0, 34.6608238491206)
RELAX_protein_RPIA_pc (0.0, 25.9591134210544)
RELAX_protein_SCN4A_pc (0.0, 4.15258744013257)
RELAX_protein_SCN9A_pc (0.0, 3.81565882563845)
RELAX_protein_SLC16A1_pc (0.0, 16.0086988060099)
RELAX_protein_SLC16A7_pc (-3.552713678800501e-15, 16.5418230690863)
RELAX_protein_SLC22A4_pc (0.0, 13.8964821671235)
RELAX_protein_SLC29A1_pc (0.0, 17.1975384883023)
RELAX_protein_SLC2A1_pc (0.0, 15.9685803655623)
RELAX_protein_SLC2A14_pc (0.0, 15.3356645046383)
RELAX_protein_SLC2A2_pc (0.0, 15.0237344485251)
RELAX_protein_SLC2A3_pc (0.0, 16.0176033182031)
RELAX_protein_SLC2A4_pc (0.0, 15.7655787142391)
RELAX_protein_SLC43A3_pc (-5.551115123125783e-17, 15.8379648491767)
RELAX_protein_SOD1_pc (0.0, 54.2217832365731)
RELAX_protein_STEAP3_pc (0.0, 15.8171490683381)
RELAX_protein_TALDO1_pc (0.0, 23.0096144326213)
RELAX_protein_TKT_pc (0.0, 12.7247261698864)
RELAX_protein_TMEM109_pc (0.0, 32.9431540269415)
RELAX_protein_TPI1_pc (0.0, 32.3879577991567)
RELAX_protein_TRPC6_pc (0.0, 8.12406842480795)
RELAX_protein_TRPV2_pc (0.0, 10.047547305579)
RELAX_protein_VDAC1_pc (0.0, 28.0656489891217)

#### Generate results for subset of PC model reactions
##### Reactions necessary for all flux-expression correlation computations.
To reduce computation time, a subset of reactions can be defined. 
For flux-expression correlations, the minimum reaction set are reactions associated with genes associated and the corresponding enzyme dilution reaction for total enzyme.

In [9]:
enzyme_total_suffix = DEFAULT_ENZYME_TOTAL_SUFFIX
min_reaction_list = model.reactions.query(lambda x: x.gene_reaction_rule).list_attr(
    "id"
)
enzymes_list = pcmodel.reactions.query(
    lambda x: x.id.startswith(f"ENZDL_enzyme_") and f"{enzyme_total_suffix}" in x.id
).list_attr("id")
reaction_enzymes_map = {
    rid: tuple(
        pcmodel.reactions.query(
            lambda x: x.id.startswith(f"ENZDL_enzyme_{rid}_")
        ).list_attr("id")
    )
    for rid in min_reaction_list
}
enzyme_reaction_map = {
    enzyme: rid for rid, enzymes in reaction_enzymes_map.items() for enzyme in enzymes
}
if not enzymes_list:
    enzymes_list = [
        enzyme
        for enzyme, rid in enzyme_reaction_map.items()
        if rid in min_reaction_list
    ]
min_reaction_list += enzymes_list
print(
    f"Number of reactions minimize/maximize (minimum): {len(min_reaction_list)} / {len(pcmodel.reactions)}"
)

Number of reactions minimize/maximize (minimum): 122 / 972

In [10]:
pcmodel_dataset_parameterized.reactions.get_by_id(
    "PBDL_relaxation_budget"
).upper_bound = pcmodel_dataset_parameterized.reactions.get_by_id(
    "PBDL_relaxation_budget"
).lower_bound

In [11]:
pcmodel_dataset_parameterized.optimize()
# pcmodel.objective.expression

## Run pcFVA

In [12]:
from cobra.flux_analysis import flux_variability_analysis

In [13]:
verbose = True
optimum_percents = [0, 0.5, 0.9, 0.99]
reaction_list = min_reaction_list.copy()

pcfva_results_dirpath = Path(f"{dataset_path}/pcFVA")

pcfva_solutions = {}

index_cols = ["reactions", "optimum", "model"]
print("================================================")
print(f"Computing pcFVA results for {pcmodel_dataset_parameterized}")
print("================================================")
try:
    optimum_solutions = []
    if verbose:
        print(f"Starting simulations for {pcmodel_dataset_parameterized}")
    for optimum_percent in optimum_percents:
        pcfva_sol = flux_variability_analysis(
            pcmodel_dataset_parameterized,
            reaction_list=reaction_list,
            loopless=False,
            fraction_of_optimum=optimum_percent,
            processes=32,
        )
        pcfva_sol.index = pd.MultiIndex.from_tuples(
            [
                (rid, optimum_percent, pcmodel_dataset_parameterized.id)
                for rid in pcfva_sol.index
            ],
            names=index_cols,
        )
        optimum_solutions.append(pcfva_sol)
        if verbose:
            print(f"Finished pcFVA for percent optimum: {optimum_percent}.")
    pcfva_sol = pd.concat(optimum_solutions, axis=0)
    filepath = Path(
        f"{pcfva_results_dirpath}/{pcmodel_dataset_parameterized}_FVAresults.tsv"
    )
    pcfva_sol.to_csv(filepath, sep="\t", index=True)
    pcfva_solutions[str(pcmodel_dataset_parameterized)] = pcfva_sol
    if verbose:
        print(f"Finished all simulations for {pcmodel_dataset_parameterized}")
except Exception as e:
    if verbose:
        print(f"{pcmodel_dataset_parameterized} failed due to an exception. {str(e)}\n")
    with open(f"{pcfva_results_dirpath}/pcFVA-errors.log", "a") as file:
        file.write(
            f"{pcmodel_dataset_parameterized} failed due to an exception. {str(e)}\n"
        )

================================================
Computing pcFVA results for RBC3P_expanded_PC_RBComics_G6PD
================================================
Starting simulations for RBC3P_expanded_PC_RBComics_G6PD
Finished pcFVA for percent optimum: 0.
Finished pcFVA for percent optimum: 0.5.
Finished pcFVA for percent optimum: 0.9.
Finished pcFVA for percent optimum: 0.99.
Finished all simulations for RBC3P_expanded_PC_RBComics_G6PD

In [14]:
groupby_list = ["model", "reactions"]

# Initialize entries with prefixes used for seperating DataFrames
dict_of_dataframes_types = {
    "reactions": None,
    "proteins": "PROTDL",
    # "complexes": "CPLXFM",
    # "complex_dilutions": "CPLXDL",
    "enzymes": "ENZDL",
    # "enzyme_formation": "ENZFM",
    "budgets": "PBDL",
    "relaxation": "RELAX",
}
df_pcfva_all = pcfva_sol.reset_index(drop=False)
for key, prefix in dict_of_dataframes_types.copy().items():
    if prefix:
        df = df_pcfva_all[
            df_pcfva_all["reactions"].apply(lambda x: x.startswith(prefix))
        ]
    else:
        df = df_pcfva_all[
            df_pcfva_all["reactions"].apply(lambda x: x in model.reactions)
        ]
    dict_of_dataframes_types[key] = df.copy()

dict_of_dataframes_types

# Get the maximum value of the reaction flux in each direction, regardless of percent optimum
df = dict_of_dataframes_types["reactions"].copy()
df = df.groupby(groupby_list)[["minimum", "maximum"]].agg(
    {
        "minimum": "min",
        "maximum": "max",
    }
)
df_max_flux_per_model = df.abs().max(axis=1)
df_max_flux_per_model.name = "Flux"
df_max_flux_per_model

# Determine flux range
df = dict_of_dataframes_types["reactions"].copy()
df["Range"] = df["maximum"] - df["minimum"]
df_flux_range_per_model = df.groupby(groupby_list)["Range"].max()
df_flux_range_per_model

# Determine span association with reaction
df = dict_of_dataframes_types["enzymes"].copy()
df["reactions"] = df["reactions"].apply(lambda x: enzyme_reaction_map[x])
df_max_enzyme_per_model = df.groupby(groupby_list)["maximum"].max()
df_max_enzyme_per_model.name = "Expression"
df_max_enzyme_per_model

df_reaction_flux_expression = (
    pd.merge(
        df_max_flux_per_model,
        df_flux_range_per_model,
        left_index=True,
        right_index=True,
    )
    .merge(df_max_enzyme_per_model, left_index=True, right_index=True)
    .reset_index(drop=False)
)
df_reaction_flux_expression

                              model reactions      Flux     Range  Expression
0   RBC3P_expanded_PC_RBComics_G6PD       ADA  0.246554  0.246554    1.822657
1   RBC3P_expanded_PC_RBComics_G6PD      ADEt  0.026166  0.026166    4.519603
2   RBC3P_expanded_PC_RBComics_G6PD      ADK1  0.026166  0.026166   45.174976
3   RBC3P_expanded_PC_RBComics_G6PD     ADNK1  0.026166  0.026166    1.406443
4   RBC3P_expanded_PC_RBComics_G6PD      ADNt  0.246554  0.272720    3.812744
..                              ...       ...       ...       ...         ...
56  RBC3P_expanded_PC_RBComics_G6PD     SPODM  0.061609  0.061609   52.129115
57  RBC3P_expanded_PC_RBComics_G6PD      TALA  0.037036  0.050744    3.367204
58  RBC3P_expanded_PC_RBComics_G6PD      TKT1  0.037036  0.050744    1.415201
59  RBC3P_expanded_PC_RBComics_G6PD      TKT2  0.037036  0.050744    1.415201
60  RBC3P_expanded_PC_RBComics_G6PD       TPI  0.036506  0.036506   17.563778

[61 rows x 5 columns]